# Generated by Django 2.1.7 on 2019-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户姓名')),
                ('WX_nickname', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='微信昵称')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], max_length=32, null=True, verbose_name='性别')),
                ('age', models.CharField(blank=True, max_length=32, null=True, verbose_name='年龄')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='所在城市')),
                ('create_time', models.DateTimeField(blank=True, max_length=32, null=True, verbose_name='创建日期')),
                ('vip_grade', models.CharField(blank=True, choices=[('1', '黄金会员'), ('2', '白金会员'), ('3', '钻石会员')], default='', max_length=32, null=True, verbose_name='用户会员登记')),
                ('is_test', models.CharField(blank=True, choices=[('1', '测试用户'), ('0', '非测试用户')], default='0', max_length=32, null=True, verbose_name='是否测试用户')),
            ],
        ),
    ]
