# Generated by Django 2.1.3 on 2019-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessFrequencyVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('Access_time', models.DateField(verbose_name='访问时间')),
                ('Number_of_visits', models.IntegerField(max_length=32)),
            ],
        ),
    ]
