# Generated by Django 2.1.3 on 2019-11-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_accessfrequencyverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessfrequencyverification',
            name='Access_time',
            field=models.DateTimeField(verbose_name='访问时间'),
        ),
    ]
