# Generated by Django 2.1.3 on 2019-11-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20191123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessfrequencyverification',
            name='Number_of_visits',
            field=models.IntegerField(verbose_name='访问次数'),
        ),
    ]
