# Generated by Django 2.1.3 on 2019-11-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20191123_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessfrequencyverification',
            name='Number_of_visits',
            field=models.CharField(max_length=256, verbose_name='访问次数'),
        ),
    ]
