# Generated by Django 2.1.3 on 2019-11-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191123_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessfrequencyverification',
            old_name='Number_of_visits',
            new_name='Number_visits',
        ),
    ]
