# Generated by Django 2.1.7 on 2019-12-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_customer_fooddetails_order_orderreplyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
